# Generated by Django 4.2.7 on 2023-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactor',
            name='year_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
