# Generated by Django 4.2.7 on 2023-11-22 10:48

from django.db import migrations, models
import newspaper.models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_newspaper_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(upload_to=newspaper.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
