# Generated by Django 4.2.7 on 2023-11-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_alter_newspaper_image_alter_newspaper_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactor',
            name='year_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
