# Generated by Django 4.2.7 on 2023-11-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0006_alter_newspaper_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ['-published_date']},
        ),
    ]
