# Generated by Django 4.2.7 on 2023-11-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_alter_newspaper_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redactor',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'redactor', 'verbose_name_plural': 'redactors'},
        ),
    ]
