# Generated by Django 4.2.7 on 2023-11-23 12:26

from django.db import migrations, models
import newspaper.models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0008_alter_redactor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=newspaper.models.generate_unique_filename),
        ),
    ]
